### ISSUE TITLE
Installation problems with anaconda

### ISSUE THREAD

**Issue by tgalery** [aboSamoor/pycld2#2]
Hi, I'm installing this package with miniconda's pip and I run into this error

```
/home/preceptor/miniconda2/envs/wiki/lib/python2.7/site-packages/polyglot/detect/base.py in <module>()
     10 
     11 from icu import Locale
---> 12 import pycld2 as cld2
     13 
     14 logger = logging.getLogger(__name__)

/home/preceptor/miniconda2/envs/wiki/lib/python2.7/site-packages/pycld2/__init__.py in <module>()
----> 1 from ._pycld2 import DETECTED_LANGUAGES, ENCODINGS, LANGUAGES, VERSION, detect, error
      2 
      3 __all__ = ['DETECTED_LANGUAGES',
      4            'ENCODINGS',
      5            'LANGUAGES',

ImportError: /home/preceptor/miniconda2/envs/wiki/lib/python2.7/site-packages/pycld2/_pycld2.so: undefined symbol: PyUnicodeUCS2_FromString
```

However when I clone the repo and run seteup.py it works. Might be a distribution thing.

**Comment by davidpgero** [comment]
Similar issue on Ubuntu 16.04 LTS. I install it with pip. 

`pip install "pycld2==0.31"`

With `Anaconda 4.2.0`, I will get this error:
`/home/{your_username}/anaconda3/lib/python3.5/site-packages/pycld2/_pycld2.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm`


With `Anaconda 4.1.1`, it works well.

**Comment by davidlinhl** [comment]
Py 2.7, centos fresh install 
running the code provided in readme

[root@instance-1y0an0zl pdsrv]# python pyclient.py 
sh: patchelf: command not found
Traceback (most recent call last):
  File "pyclient.py", line 4, in <module>
    client.load_client_config("uci_housing_client/serving_client_conf.prototxt")
  File "/usr/lib/python2.7/site-packages/paddle_serving_client/__init__.py", line 90, in load_client_config
    from .serving_client import PredictorClient
ImportError: /usr/lib/python2.7/site-packages/paddle_serving_client/serving_client.so: undefined symbol: PyUnicodeUCS2_FromString
